### ISSUE TITLE
Minesweeper Details

### ISSUE THREAD

**Issue by jonpchin** [UCF-Software-Architects/Minesweeper#1]
For our first project we are doing Minesweeper in Java.

First thing first, everyone needs to list what IDE they prefer to use for Java and what operating system they run and also list any coding styles, indentation styles, etc. I'll go first.

1. IDE: Netbeans
2. Operating System: Windows 8 and Ubuntu Linux
3. Variable Naming: camelCase but I am also comfortable with under_scores
4. Indentations: 
   while(){

    }
but I am also comfortable with
   while()
   {

   }

We will be using Git for version source control though you can use what you want just let everyone know. If you never played Minesweeper I HIGHLY recommend reading up on it otherwise you won't know whats going on. 

Minesweeper Implementations:
1. For the GUI a 2D static array of buttons which can be clicked.
2. We need backend function to randomly setup the 2D array with bombs and the rest will be left blanks. Numbers will be then placed to indicate how many bombs are adjacent to it horizontally, vertically and diagonally. 
3. Top menu bar allows player to "Play Game" or "Quit"
4. Score and timer are on the top
5. When a player clicks "New Game" the buttons will be enabled and timer will start.
6. IMPORTANT: When a player clicks on a button with a blank, a flood fill algorithm will occur to unlock adjacent blank squares.  
7. If a player clicks on a a bomb they lose the game and the entire 2D array of buttons will be revealed. Timer will stop and player score will be shown.
8. If a player clicks on  a number then just that button will be revealed to them.
9.. Allow player to mark flags on non clicked buttons by right clicking.

If I am missing any other details please discuss below. All opinions are highly appreciated. Also since this is our first project as a team, it is mandatory that everyone use LOTS of comments.

Nobody should push, clone or write any code until Thursday. These next three days are just discussing how we will go about implementing Minesweeper.

**Comment by FultonG** [comment]
1. IDE: IntelliJ IDEA
2. Operating System: OSX, Windows 10, Ubuntu Linux
3. Variable naming: prefer camelCase
4. Indentations:
for(int x = 1; x < 101; x++){
    squares += Math.pow(x, 2);
    sums += x;
 }

**Comment by FultonG** [comment]
1. IDE: IntelliJ IDEA
2. Operating System: OSX, Windows 10, Ubuntu Linux
3. Variable naming: prefer camelCase
4. Indentations:

        while(){
        //insert that code here
        }

**Comment by mateov1995** [comment]
IDE: Eclipse
OS: Windows 8
Variable naming: camelCase
Indentations:
while()
{

}

**Comment by FultonG** [comment]
How are we going to be implementing the GUI? Using JavaFx I assume?

**Comment by jonpchin** [comment]
For the GUI we can use JavaFx or Swing. I have some experience in Swing. Swing is fully featured and well supported and its been around longer then JavaFx. But its easier to do animations, videos, and transitions in JavaFx then Swing. JavaFx is new but will slowly overtake Swing in the future. 

If the group wants to go the traditional route without any surprises Swing is the way to go. I am also fine using JavaFx as I have an itch to learn something new.

**Comment by FultonG** [comment]
I've done a bit of JavaFx for a java class but that was a while ago so I would have to relearn it. Never done swing so whichever works with everyone else is fine by me

**Comment by jonpchin** [comment]
I want to make one important before anyone pushes anything. If we all use different IDE's we have to be cautious about pushing entire projects because each IDE has special project configurations. 
I have Eclipse and I don't mind downloading IntelliJ IDEA to use. 

We have two options. One we can all switch to use the same IDE. Option two, we have to only push the src folder and not the entire project folder. The second option makes more sense if everyone is really picky on which IDE they use. Otherwise the first option makes most sense.

**Comment by jonpchin** [comment]
Just to make everyone's lives easier lets go with the second option so we don't have to force people to switch IDE.

**Comment by mateov1995** [comment]
Yes I agree

**Comment by jonpchin** [comment]
On the top menu the player will be choose between three levels, easy(9x9 grid 10 bombs), intermediate(16x16 grid, 40 bombs), expert(16x30, 99 bombs). Also we will be using Swing for this project. In the future if we ever use Java again to make it a GUI we will use JavaFX.

**Comment by FultonG** [comment]
Do you have any suggestions of reference material for swing? I want to start looking into it

**Comment by jonpchin** [comment]
You can take a look at http://docs.oracle.com/javase/tutorial/uiswing/
There are other good tutorials on Swing. 

For those who are not familiar with Java we will be starting another project in about a week. In order to speed things up and skip a two step voting process I have chosen Python. And yes, I aware this is a new language for many people in the group.  We will have a one week voting period on what project to do it in. You can send me a message on facebook or if you prefer to post here publicly you can do that as well.

**Comment by jonpchin** [comment]
Minesweeper is almost done. I am using cardlayout to switch between the three levels. I am currently working on floodfill algorithm. There are three ways to implement it, one of the ways which uses full recursion may cause the stack to overflow in the large board so we will use a different way.

I uploaded the flag.png so if anyone wants to work on implementing the right click on the JToggleButtons to place a flag then feel free. We also have no timer and no scoreboard so someone can implement that.

Once I finish the recursive floodfill algorithm and then right click flag option on the JToggleButton with the timer/scoreboard is completed then MineSweeper will be finished. I'll then setup a website for us so we can host our finished product for anyone to download.

**Comment by jonpchin** [comment]
Floodfill algorithm completed. If anyone here wants to test out the game feel free. Its fully playable. No right click for flags yet.

**Comment by jonpchin** [comment]
To those who don't know how to compile the source code in Java I have released a Jar file which can be run as long as the person has JRE(Java Runtime environment) installed on their computer.

The link to the Minesweeper beta version is:
https://github.com/UCF-Software-Architects/Minesweeper/releases

Once the feature to detect if the player has won the game is implemented I'll release a final version.

**Comment by jonpchin** [comment]
I deleted all the previous commits by accident while trying to update the master branch. The most important working final version copy is there but all previous versions are gone. I just wanted everyone to be aware of that.

**Comment by jonpchin** [comment]
I'll be more careful next time.

**Comment by jonpchin** [comment]
Minesweeper is completed. Feel free to download and play.
